name: Ruby

on:
  push:
    branches:
      - '*'
  schedule:
    - cron:  '6 */2 * * *'
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: install gems
      run: |
        bundle install
    - name: run script
      run: |
        ./aggregate-data
